/* generated by atlas.py build: edit .atlas/src/, not this file */
window.ATLAS = {
 "site": {
  "repo": "CVgen",
  "title": "How CVgen works",
  "tagline": "Premium, hand-crafted CVs made with AI on our own Typst `Framework`. Five questions, answered as pictures: what to do with a new `Client`, what happens to a design run, how any change lands, how the parts connect, and who does the work.",
  "lang": "en",
  "sourceBase": "../",
  "branch": "main",
  "snapshot": {
   "asOf": "2026-10-06",
   "note": "Read from main on 2026-10-04, after every open branch was merged into it; the task-store pages were updated on 2026-10-06 for the move to Backlog.md (ADR 0014). Client data is never shown here: a client is only their `Alias`."
  },
  "sources": [
   "AGENTS.md",
   "docs/glossary.md"
  ],
  "pages": [
   "client-journey",
   "design-run",
   "change-review",
   "system-map",
   "roster"
  ],
  "moves": [
   {
    "title": "Look through the 18 designs in the Design Review app",
    "detail": "Optional, any time: mark keep, maybe or reject; agents read your verdicts. You said you would do it later (2026-10-01).",
    "to": "design-run#own-look",
    "optional": true
   }
  ],
  "actors": {
   "owner": {
    "label": "You",
    "kind": "owner",
    "role": "The product owner. The only one who talks to a `Client`, picks the designs and approves a real client's PDF.",
    "notes": [
     "Owner-only: `Approval` of a real client's PDF, product decisions, deleting anything under `private/`, replacing the `Release`.",
     "Everything routine (commits, merges to `main`, task-store updates) is the agents' job."
    ],
    "sources": [
     "docs/preferences.md:49-78",
     "docs/guides/client-workflow.md:9-10"
    ],
    "short": "You"
   },
   "client": {
    "label": "The client",
    "kind": "client",
    "role": "The person the CV is for. Answers the questions, checks the facts in the `Text Draft`, says OK.",
    "notes": [
     "Gets at most three messages before `Sign-off`: the question list, one follow-up, the `Text Draft` (plus a corrected draft if asked).",
     "Outside `private/` a client is only their `Alias`, like `client-2026-09-01`."
    ],
    "sources": [
     "docs/guides/client-workflow.md:316-318",
     "docs/guides/client-workflow.md:63-67"
    ],
    "short": "Client"
   },
   "lead": {
    "label": "Claude (lead)",
    "kind": "lead",
    "model": "Session model",
    "role": "The main Claude Code session you talk to. Plans, writes, researches, builds, runs the review loops and integrates.",
    "notes": [
     "Runs on whatever model the session uses; the repo pins no model for the lead.",
     "Starts every session from the `session-handoff` doc on `main` (`backlog/docs/`) and rewrites it before stopping."
    ],
    "sources": [
     "AGENTS.md:28-44",
     "docs/development.md:34-56"
    ],
    "short": "Claude"
   },
   "magazine-editor": {
    "label": "magazine-editor",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/magazine-editor.md",
    "role": "Art director. Draws three very distinct `Styles`, each in two `Densities` and three `Design Tiers`: 18 real Typst mock-ups on fictional data.",
    "tools": "Read, Grep, Glob, Bash, PowerShell, WebSearch, WebFetch, Write, Edit",
    "access": "Writes only its concept folders, the concepts README and fonts. Never git, the `backlog` CLI or `private/`.",
    "calledBy": "The lead, through the `idea-run` skill.",
    "when": "A design run, for inspiration or for a client whose `Domain` has no `Template` yet.",
    "sources": [
     ".claude/agents/magazine-editor.md:1-23",
     ".claude/agents/magazine-editor.md:50-82"
    ],
    "short": "Editor",
    "notes": [
     "The two `Densities` (18 designs per run) were added on 2026-09-29 and reached `main` on 2026-10-04."
    ]
   },
   "design-reviewer": {
    "label": "design-reviewer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/design-reviewer.md",
    "role": "Art-direction gate. Judges every page on the `Batch Test`, the `Three-Second Test` and `Flagship Parity` first; any of those failing is Blocking.",
    "tools": "Read, Grep, Glob, Bash, PowerShell, WebFetch",
    "readOnly": true,
    "calledBy": "The lead: a fresh one every round.",
    "when": "Design runs, client designs, Flagship changes, brand assets.",
    "notes": [
     "Rubric: 1 `Batch Test`, 2 `Three-Second Test`, 3 `Flagship Parity`, 4 distinct, 5 reads as a CV, 6 craft, 7 provenance, 8 buildable and honest.",
     "Makes batch sheets: each page shrunk among 8+ plain market CVs."
    ],
    "sources": [
     ".claude/agents/design-reviewer.md:1-17",
     ".claude/agents/design-reviewer.md:66-133"
    ],
    "short": "Design rev."
   },
   "research-reviewer": {
    "label": "research-reviewer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/research-reviewer.md",
    "role": "Checks that every source exists, is current and says what is claimed.",
    "tools": "Read, Grep, Glob, WebSearch, WebFetch",
    "readOnly": true,
    "calledBy": "The lead: a fresh one every round.",
    "when": "A design run's references, a client's `Deep Dives`, `Research Library` notes.",
    "notes": [
     "Never reads `private/`: the lead passes client research inline, checked for client details, with its SHA-256."
    ],
    "sources": [
     ".claude/agents/research-reviewer.md:1-20"
    ],
    "short": "Research rev."
   },
   "ceo": {
    "label": "ceo",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/ceo.md",
    "role": "Product strategist. Proposes at most three researched product ideas as pending proposals.",
    "tools": "Read, Grep, Glob, WebSearch, WebFetch, Write, Edit",
    "access": "Writes only in its run folder. No shell.",
    "calledBy": "The lead, through the `idea-run` skill.",
    "when": "A product `Idea Run`, weekly at most.",
    "sources": [
     ".claude/agents/ceo.md:1-17"
    ]
   },
   "ceo-reviewer": {
    "label": "ceo-reviewer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/ceo-reviewer.md",
    "role": "Judges each product idea: real need, fit, honest smallest version, not a duplicate, decision-ready.",
    "tools": "Read, Grep, Glob, WebFetch",
    "readOnly": true,
    "calledBy": "The lead.",
    "when": "A product `Idea Run`.",
    "sources": [
     ".claude/agents/ceo-reviewer.md:1-7",
     ".claude/agents/ceo-reviewer.md:32-59"
    ]
   },
   "code-reviewer": {
    "label": "code-reviewer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "file": ".claude/agents/code-reviewer.md",
    "role": "The independent review gate for every non-trivial change. Fresh context, eight lenses, verdict PASS or FINDINGS.",
    "tools": "Read, Grep, Glob, Bash, PowerShell",
    "readOnly": true,
    "calledBy": "The lead: a fresh one every round, never a fork, never self-review.",
    "when": "Code, tests, fixtures, and on `main` every other change no other gate covers.",
    "notes": [
     "May rerun vetted checks that write only under `builds/`.",
     "Opus at high is the owner's standing choice for reviewers (since 2026-09-26)."
    ],
    "sources": [
     ".claude/agents/code-reviewer.md:1-7",
     "docs/review.md:126-144"
    ],
    "short": "Code rev."
   },
   "repo-auditor-lite": {
    "label": "repo-auditor-lite",
    "kind": "agent",
    "model": "Session model",
    "effort": "medium",
    "file": ".claude/agents/repo-auditor-lite.md",
    "role": "Read-only repository auditor with no shell. Does the judgement checks after the audit script ran.",
    "tools": "Read, Glob, Grep",
    "readOnly": true,
    "calledBy": "The `repo-maintenance` skill (`audit`, `deep`).",
    "when": "Tidy-ups and audits.",
    "notes": [
     "Inherits the session's model at medium effort: fine, it never gives a review verdict."
    ],
    "sources": [
     ".claude/agents/repo-auditor-lite.md:1-10"
    ]
   },
   "context-reviewer": {
    "label": "context-reviewer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "status": "built",
    "file": ".claude/agents/context-reviewer.md",
    "role": "Review gate for agent context: AGENTS.md, docs rules, glossary, skills, agent files. Checks placement, terms and that no client leaks.",
    "tools": "Read, Grep, Glob, Bash, PowerShell",
    "readOnly": true,
    "calledBy": "The lead.",
    "when": "Any change to the files agents read.",
    "notes": [
     "Merged into `main` on 2026-10-04 (owner's decision). The two review reports from its branch were FINDINGS and stay open: `docs/work/codex-visual-tools/reviews/01.md`."
    ],
    "sources": [
     ".claude/agents/context-reviewer.md",
     "docs/work/anti-examples/reviews/01-context.md"
    ],
    "short": "Context rev."
   },
   "context-maintainer": {
    "label": "context-maintainer",
    "kind": "agent",
    "model": "Opus",
    "effort": "high",
    "status": "built",
    "file": ".claude/agents/context-maintainer.md",
    "role": "Puts your feedback into the one file that owns the rule. Consolidates, never appends.",
    "tools": "Read, Grep, Glob, Edit, Write, Bash, PowerShell",
    "calledBy": "The lead.",
    "when": "Feedback from you that changes how agents behave.",
    "notes": [
     "Merged into `main` on 2026-10-04 (owner's decision). The two review reports from its branch were FINDINGS and stay open: `docs/work/codex-visual-tools/reviews/01.md`."
    ],
    "sources": [
     ".claude/agents/context-maintainer.md"
    ]
   },
   "general-purpose": {
    "label": "general-purpose",
    "kind": "agent",
    "model": "Session model",
    "role": "Claude Code's built-in agent. Writes each `Deep Dive`, can run the `Scout`, and stands in for any agent file not loaded yet.",
    "calledBy": "The lead.",
    "notes": [
     "As a stand-in it is told to act exactly as the agent file, with that file's tools as a hard limit, and the lead records its model and effort."
    ],
    "sources": [
     ".claude/skills/new-client/SKILL.md:34-47",
     ".claude/skills/idea-run/SKILL.md:87-104"
    ],
    "short": "General"
   },
   "codex-reviewer": {
    "label": "codex-visual-reviewer",
    "kind": "external",
    "model": "GPT-6 Astra",
    "effort": "high",
    "status": "planned",
    "role": "Second visual reviewer beside the design-reviewer: looks at the page images through the Codex CLI. A design round passes only when both pass.",
    "access": "Read-only sandbox.",
    "calledBy": "The lead, every design round (once built).",
    "notes": [
     "Approved by you on 2026-09-29, not built. The proposal has two open Material findings: run with `--ephemeral` and `--ignore-user-config`."
    ],
    "sources": [
     "docs/proposals/codex-visual-tools.md",
     "docs/work/codex-visual-tools/reviews/01.md"
    ],
    "short": "Codex rev."
   },
   "codex-image": {
    "label": "Codex image step",
    "kind": "external",
    "model": "GPT-6 Sol",
    "effort": "high",
    "status": "planned",
    "role": "Generates raster images a design commissions: never a portrait, no real people, brands or text, at most two per page.",
    "calledBy": "The magazine-editor commissions images; the lead does for client designs (once built).",
    "notes": [
     "Approved 2026-09-29, not built."
    ],
    "sources": [
     "docs/proposals/codex-visual-tools.md"
    ]
   },
   "new-client": {
    "label": "new-client",
    "kind": "skill",
    "file": ".claude/skills/new-client/SKILL.md",
    "role": "Checklist from a client's first message to signed-off facts: `Envelope`, `Intake`, research, `Text Draft`, `Sign-off`.",
    "when": "You say a new client arrived, or ask to continue their intake or research.",
    "notes": [
     "Every time it runs it also checks for stalled clients (3 months, no `Export`) and passed delete-by dates."
    ],
    "sources": [
     ".claude/skills/new-client/SKILL.md:1-9",
     ".claude/skills/new-client/SKILL.md:95-98"
    ]
   },
   "new-cv": {
    "label": "new-cv",
    "kind": "skill",
    "file": ".claude/skills/new-cv/SKILL.md",
    "role": "Checklist that builds the CV itself: data, entry point, page plan, the client design loop, the render and its evidence.",
    "when": "After `Sign-off`, or to add a public example.",
    "sources": [
     ".claude/skills/new-cv/SKILL.md:1-15"
    ]
   },
   "idea-run": {
    "label": "idea-run",
    "kind": "skill",
    "file": ".claude/skills/idea-run/SKILL.md",
    "role": "Runs an idea agent (magazine-editor or ceo) in a closed review loop. Authors propose, reviewers judge, you decide.",
    "when": "You ask for design concepts, template inspiration or product ideas.",
    "sources": [
     ".claude/skills/idea-run/SKILL.md:1-21"
    ]
   },
   "verify-cv": {
    "label": "verify-cv",
    "kind": "skill",
    "file": ".claude/skills/verify-cv/SKILL.md",
    "role": "Runs the full suite and reads its evidence.",
    "when": "After any change under `packages/`, `examples/` or `tests/`.",
    "sources": [
     ".claude/skills/verify-cv/SKILL.md:1-17"
    ]
   },
   "new-theme": {
    "label": "new-theme",
    "kind": "skill",
    "file": ".claude/skills/new-theme/SKILL.md",
    "role": "Adds a `Theme` or `Artwork Pack` and proves the `Frozen Reference` is untouched.",
    "when": "A new look, colour scheme or role illustrations.",
    "sources": [
     ".claude/skills/new-theme/SKILL.md:1-5"
    ]
   },
   "backlog": {
    "label": "backlog",
    "kind": "skill",
    "file": ".claude/skills/backlog/SKILL.md",
    "role": "Reads and updates the tasks in `backlog/` through the `backlog` CLI, and reads and rewrites the `session-handoff` doc on `main`. Every task's record is a task file.",
    "when": "Orientation, and every task state change.",
    "sources": [
     ".claude/skills/backlog/SKILL.md:1-116"
    ]
   },
   "repo-maintenance": {
    "label": "repo-maintenance",
    "kind": "skill",
    "file": ".claude/skills/repo-maintenance/SKILL.md",
    "role": "Keeps the tree easy to navigate: a read-only audit (`quick`, `audit`, `deep`), then `apply` moves only what you approved by ID.",
    "when": "`quick` in every `Session Sweep`; the rest when you ask for a tidy-up.",
    "sources": [
     ".claude/skills/repo-maintenance/SKILL.md:21-28",
     ".claude/repo-maintenance.md:136-140"
    ]
   },
   "night-shift": {
    "label": "Night Shift skills",
    "kind": "skill",
    "file": ".claude/skills/start-night-shift/SKILL.md",
    "role": "Unattended overnight work (`start-night-shift`) and its follow-up by day (`do-night-shift-follow-up`).",
    "when": "You say \"start night shift\".",
    "sources": [
     ".claude/skills/start-night-shift/SKILL.md:1-5",
     ".claude/skills/do-night-shift-follow-up/SKILL.md:1-5"
    ]
   },
   "cv-py": {
    "label": "scripts/cv.py",
    "kind": "tool",
    "file": "scripts/cv.py",
    "role": "`render`, `approve`, `export`, `status` for one client's `Envelope`. Each render is a new `Revision`; it never overwrites.",
    "notes": [
     "Exit 1: compile or checks failed, the `Revision` is kept. Exit 2: refused, nothing written."
    ],
    "sources": [
     "scripts/cv.py:1-12",
     "docs/guides/build-a-cv.md:117-206"
    ]
   },
   "outputs-py": {
    "label": "scripts/outputs.py",
    "kind": "tool",
    "file": "scripts/outputs.py",
    "role": "The `Output Contract` tool: `stamp` writes a PDF's `Meta File`; `check` lists every PDF without a valid one.",
    "sources": [
     "scripts/outputs.py",
     "docs/pdf-workflow.md:123-156"
    ]
   },
   "suite": {
    "label": "tests/run.py",
    "kind": "tool",
    "file": "tests/run.py",
    "role": "The full test suite: compiles every example, checks the `Frozen Reference` pixel for pixel, the workflow, the contract. Evidence goes to `builds/tests-<timestamp>/`.",
    "sources": [
     "tests/run.py",
     "docs/reference/verification.md"
    ]
   },
   "design-review-app": {
    "label": "Design Review app",
    "kind": "tool",
    "file": "scripts/design_review/server.py",
    "role": "Your local app for looking through designs: the Board (`Style` × `Density` × `Design Tier`), the Loupe, compare, a `Batch Test` pile, your verdicts and notes.",
    "notes": [
     "`python scripts/design_review/server.py`, then http://127.0.0.1:8765/. Binds to this machine only.",
     "Your verdicts (keep / maybe / reject) live in `.local/design-review/state.json`."
    ],
    "sources": [
     "scripts/design_review/server.py:1-12",
     "AGENTS.md"
    ]
   },
   "build-ps1": {
    "label": "scripts/build.ps1",
    "kind": "tool",
    "file": "scripts/build.ps1",
    "role": "Builds the five public examples into `builds/`; with `-Release` it copies them beside their entry points and stamps them.",
    "sources": [
     "scripts/build.ps1"
    ]
   },
   "intake-form": {
    "label": "Intake Form script",
    "kind": "tool",
    "file": "scripts/intake-form.gs",
    "role": "Google Apps Script you run once per form: builds the optional `Intake Form` and its answers Sheet in your Google account.",
    "sources": [
     "scripts/intake-form.gs:1-21",
     "docs/guides/client-workflow.md:91-128"
    ]
   },
   "board": {
    "label": "Task store `backlog/`",
    "kind": "service",
    "role": "The task store (Backlog.md, ADR 0014): one file per task, statuses Queued, Active, Review, Ready, Done, label `blocked`. The `session-handoff` doc is where every session starts. Boards: `backlog board`, `backlog browser`.",
    "sources": [
     ".claude/skills/backlog/SKILL.md:1-35",
     "docs/development.md:17-32",
     "docs/decisions/0014-backlog-md-task-store.md"
    ],
    "short": "Backlog"
   },
   "chat": {
    "label": "Chat app",
    "kind": "service",
    "role": "Viber, WhatsApp or email: how you pass questions and drafts to the client and bring answers back.",
    "sources": [
     "docs/guides/client-workflow.md:81-89"
    ],
    "short": "Chat"
   },
   "github-ci": {
    "label": "GitHub CI",
    "kind": "service",
    "role": "Runs the suite on every push and pull request (Typst 0.15.1). The lead watches it on `main` before calling work Done.",
    "sources": [
     ".github/workflows/verify.yml",
     "docs/git-workflow.md:66-79"
    ],
    "short": "CI"
   }
  },
  "terms": {
   "CVgen": "The product: premium, hand-crafted CVs built with AI on our own Typst `Framework`.",
   "Framework": "The shared Typst core every CV is built on: page frame, headings, data merge, checks. Knows no `Domain`.",
   "Domain": "A career area with its own facts shape, wording, artwork and rules: Marine, Travel & Tourism. Ids: `marine`, `travel`.",
   "Role": "One specialisation inside a `Domain`, never a fork: Deck and Engine in Marine.",
   "Rank": "The client's job title: second engineer, captain, tour guide.",
   "Template": "A named CV design. Belongs to a `Domain`, or lives in one `Envelope` as a one-off for a single client.",
   "Flagship": "The marine `Template`: the quality bar every design is measured against.",
   "Theme": "A `Template`'s colours, fonts and sizes only.",
   "Artwork Pack": "Which illustration goes in which slot of a `Template`.",
   "Client": "The person a CV is for, who also pays for it. The code says \"candidate\".",
   "Envelope": "One client's private folder: facts, portrait, `Template` tweaks, every `Revision` and `Export`. Lives in `private/`, never in Git.",
   "Alias": "The neutral name for a client outside `private/`: client-yyyy-mm-nn.",
   "Intake": "Collecting a client's facts and goals before research: a question list sent by chat, answers kept in the `Envelope`.",
   "Relay": "The `Intake` method: Claude writes the questions, you pass them to the client by chat and bring the answers back.",
   "Intake Form": "The `Relay` questions as an optional, designed Google Form, made by running a per-form Apps Script.",
   "Research Library": "Shared, dated research notes about a country, `Domain` or `Rank`, reused across clients, rechecked after 6 months. No client data.",
   "Scout": "A wide, shallow first search for one client: the `Research Library` first, the web for what is missing.",
   "CV Decisions": "The choices a CV must make (title, length, photo, language, `Template`, what leads), each sourced, a judgement, or open.",
   "Deep Dive": "One agent researching one open question, chosen by you after the `Scout`.",
   "Text Draft": "The CV's content as a PDF in the fixed house design (First Fitting) that the client checks before design starts.",
   "Check Page": "Page 1 of a `Text Draft`, in the client's language (the house copy is Greek): check only the underlined facts, reply OK.",
   "Fact Mark": "The copper stitch under a fact the client must check in a `Text Draft`.",
   "Sign-off": "The client's \"OK, the facts are correct\" on the `Text Draft`, before design starts. Usually a chat message, screenshot kept.",
   "Revision": "One render of a CV in its own folder, never overwritten.",
   "Approval": "Your act on one exact PDF, bound to its SHA-256. Agents never approve a real client's PDF.",
   "Export": "The verified copy of a client's approved PDF, ready to deliver.",
   "Release": "The public example PDFs that show the product, with fictional people.",
   "Output Contract": "Every PDF we show sits in its kind's one home and carries a `Meta File`.",
   "Meta File": "The small JSON beside a PDF saying what it is (kind, `Domain`, status, pages) with its SHA-256.",
   "Frozen Reference": "The PDF a `Template`'s public example must reproduce pixel for pixel.",
   "Framework Gap": "A recorded case of going around the `Framework`, a `Domain` or a `Template` to deliver a CV.",
   "Session Sweep": "The places to look for loose ends before a session ends: unreviewed commits, approved proposals, open tasks, Night Shift items, Git leftovers, CI, `builds/`.",
   "Certificate Warning": "A WARNING line at render: a certificate expired or expires within 180 days. Never blocks.",
   "Live Read": "A render that read a private file directly instead of the `Revision`'s copy. It fails its checks.",
   "Batch Test": "Design test 1: in an HR batch of 100 to 200 CVs, ours cannot be skipped.",
   "Three-Second Test": "Design test 2: before a word is read, the page shouts its `Domain`, specialty and role.",
   "Flagship Parity": "Design test 3: side by side with the Marine Flagship, the CV looks as confident and premium.",
   "Style": "One idea of a magazine-editor run. A run has three very distinct ones.",
   "Design Tier": "Safe (calm, never generic), Stylish (Flagship territory), Creative (style to the maximum).",
   "Density": "Condensed (one dense page) or Spacious (1 to 3 roomier pages). Every `Style` is drawn in both (since 2026-09-29).",
   "Anti-example": "A design you rejected as not your style, kept frozen only so nobody proposes its idea again.",
   "Design Review": "Your local app for looking through designs and recording verdicts.",
   "Idea Run": "One closed loop of an idea agent (ceo or magazine-editor) and its reviewers."
  },
  "modelNotes": {
   "Session model": "Whatever model your Claude Code session runs; the repo pins none. Today: Opus 5.5.",
   "Opus": "The `opus` alias in the agent files: the newest Opus, today Opus 5.5.",
   "GPT-6 Astra": "Planned, not built (approved 2026-09-29).",
   "GPT-6 Sol": "Planned, not built (approved 2026-09-29)."
  }
 },
 "pages": [
  {
   "id": "client-journey",
   "kind": "flow",
   "nav": "New client",
   "title": "A new client, start to finish",
   "question": "I just got a new client. What do I do?",
   "summary": "From the first message to the delivered PDF. You are the only one who talks to the client; Claude writes, researches and builds; nothing reaches the client or gets approved without you.",
   "tldr": [
    "Say \"new client\" to Claude. The `new-client` skill opens a private `Envelope` and writes the questions; you pass them on by chat.",
    "Research and one follow-up, then a `Text Draft`. The client checks only the facts and says OK: that is the `Sign-off`.",
    "Then the design, a `Revision`, your `Approval`, the `Export`, and you send it. Data is deleted 12 months after delivery."
   ],
   "sources": [
    "docs/guides/client-workflow.md",
    "docs/guides/build-a-cv.md"
   ],
   "status": {
    "step": "approve",
    "asOf": "2026-10-04",
    "title": "client-2026-09-01: CV built, approval and export are yours",
    "note": "Travel & Tourism, a tour leader for Japan. You chose Hanami Line 2 on 2026-10-02 (all three palettes) and the CV was built from it as a one-off `Template` in the client's `Envelope`. Approval, export and delivery happen on your machine, where `private/` lives.",
    "waitingOn": [
     "owner"
    ],
    "ref": "docs/framework-gaps.md"
   },
   "phases": [
    {
     "id": "open",
     "title": "Open",
     "steps": [
      {
       "id": "arrives",
       "title": "A new client writes to you",
       "actor": "owner",
       "with": [
        "lead"
       ],
       "summary": "Tell Claude a new client arrived: who, which job, which career area. That starts the `new-client` skill.",
       "you": "Say \"new client\" with the person's name, `Rank` and `Domain`. Everything after this is a checklist Claude follows.",
       "does": [
        "Claude loads the `new-client` checklist.",
        "It also checks every open client for a stall (no `Export` 3 months after intake) and for a passed delete-by date."
       ],
       "uses": [
        "new-client"
       ],
       "sources": [
        "docs/guides/client-workflow.md:9-10",
        ".claude/skills/new-client/SKILL.md:1-9",
        ".claude/skills/new-client/SKILL.md:95-98"
       ]
      },
      {
       "id": "envelope",
       "title": "Open the Envelope",
       "actor": "lead",
       "summary": "One private folder per client, never in Git. Outside it the client is only an `Alias`.",
       "does": [
        "Creates `private/<name>-<rank>/` with the drawers `intake/`, `research/`, `draft/`.",
        "Gives the client an `Alias` (`client-2026-09-01` style) and writes it in the folder's `README.md`.",
        "Writes `envelope.json`: alias, `Domain` id (`marine` or `travel`), name, `Rank`."
       ],
       "out": [
        "`private/<envelope>/`",
        "`envelope.json`",
        "`README.md` (alias, dates, links)"
       ],
       "note": "`scripts/cv.py render` refuses to run without `envelope.json`, and every `Meta File` in the `Envelope` copies it.",
       "uses": [
        "new-client"
       ],
       "sources": [
        "docs/guides/client-workflow.md:19",
        "docs/guides/client-workflow.md:29-77"
       ]
      }
     ]
    },
    {
     "id": "intake",
     "title": "Intake",
     "steps": [
      {
       "id": "questions",
       "title": "Write the question list",
       "actor": "lead",
       "summary": "13 questions in one message, simple friendly Greek, adapted to the `Domain`. Question 1 is consent.",
       "does": [
        "Writes the master list as one chat message.",
        "Consent first: AI tools and web research, private files, never published, deleted 12 months after delivery.",
        "Optional: a designed Google `Intake Form` instead. Claude writes `intake/form-NN.gs` from the template script."
       ],
       "out": [
        "The question message",
        "or `intake/form-NN.gs`"
       ],
       "uses": [
        "new-client",
        "intake-form"
       ],
       "sources": [
        "docs/guides/client-workflow.md:81-84",
        "docs/guides/client-workflow.md:130-156",
        "docs/guides/client-workflow.md:91-108"
       ]
      },
      {
       "id": "relay",
       "title": "Send it; the client answers",
       "actor": "owner",
       "with": [
        "client"
       ],
       "summary": "You are the relay. The client answers in any order, text or voice, over a few days.",
       "you": "Paste the message into Viber, WhatsApp or email (or run the form script at script.google.com and send the link). When answers come, copy the chat into `intake/messages.md` and photos into `intake/documents/`.",
       "gate": {
        "type": "client",
        "label": "Waits for the client's answers, usually a few days."
       },
       "does": [
        "Voice messages need a transcript: your phone's or your gist.",
        "Claude never opens the client's LinkedIn page; its PDF export is enough."
       ],
       "in": [
        "The question list"
       ],
       "out": [
        "`intake/messages.md`",
        "`intake/documents/`"
       ],
       "cmd": [
        {
         "cmd": "createIntakeForm",
         "who": "you",
         "note": "Only for the optional form: run it once in script.google.com; the log prints the client link and the answers Sheet."
        }
       ],
       "sources": [
        "docs/guides/client-workflow.md:20",
        "docs/guides/client-workflow.md:86-89",
        "docs/guides/client-workflow.md:162-163"
       ]
      },
      {
       "id": "consent",
       "title": "Consent check",
       "actor": "lead",
       "summary": "A hard stop. Nothing is read, written or researched until the client's \"I agree\" is in the `Envelope`.",
       "gate": {
        "type": "check",
        "label": "The client's \"I agree\" is in `intake/messages.md`.",
        "pass": "consent is there"
       },
       "does": [
        "No consent: you decide whether to ask again or stop."
       ],
       "sources": [
        "docs/guides/client-workflow.md:158-162",
        ".claude/skills/new-client/SKILL.md:23-25"
       ]
      }
     ]
    },
    {
     "id": "research",
     "title": "Research",
     "steps": [
      {
       "id": "facts",
       "title": "Facts and the gap list",
       "actor": "lead",
       "summary": "Every fact from the answers, each naming the message or document it came from. Nothing invented.",
       "does": [
        "Identity, target, each job with scope and results, certificates, education, languages, what may be shown.",
        "Calendar dates are never turned into service time.",
        "The gap list waits for the one follow-up, so the client is asked only once."
       ],
       "in": [
        "`intake/messages.md`",
        "`intake/documents/`"
       ],
       "out": [
        "`intake/facts.md`"
       ],
       "sources": [
        "docs/guides/client-workflow.md:167-172"
       ]
      },
      {
       "id": "scout",
       "title": "Scout",
       "actor": "lead",
       "with": [
        "general-purpose"
       ],
       "summary": "A wide, shallow search: the country's CV norms, what employers expect of this `Rank`, how CVs are sent.",
       "does": [
        "Reads the `Research Library` first; a note past its recheck date is rechecked before use.",
        "Then the web for what is missing.",
        "Web searches never contain the client's name or an identifying combination."
       ],
       "out": [
        "`research/scout.md`: numbered findings with source and date"
       ],
       "sources": [
        "docs/guides/client-workflow.md:176-184",
        "docs/guides/client-workflow.md:309-312"
       ]
      },
      {
       "id": "decisions",
       "title": "CV Decisions",
       "actor": "lead",
       "with": [
        "owner"
       ],
       "summary": "One line per choice the CV must make: title, length, photo, language, `Template`, what leads. Each sourced, a judgement, or open.",
       "you": "Pick which open decisions deserve a `Deep Dive`. Claude shows each with a recommendation.",
       "gate": {
        "type": "owner"
       },
       "out": [
        "`research/decisions.md`"
       ],
       "note": "Research is enough when every decision has an answer; a new source that changes nothing is the signal to stop.",
       "sources": [
        "docs/guides/client-workflow.md:188-206"
       ]
      },
      {
       "id": "deep-dives",
       "title": "Deep Dives",
       "actor": "general-purpose",
       "with": [
        "research-reviewer"
       ],
       "summary": "0 to 3 per client (up to 6 for an executive). One background agent per question, each checked by a fresh reviewer until PASS.",
       "does": [
        "The agent gets only the `Alias`, never the folder path.",
        "Claude checks the text for client details, then gives it to a fresh `research-reviewer` with its SHA-256.",
        "A finding about a country or `Rank` with no client detail also goes to the `Research Library`."
       ],
       "gate": {
        "type": "review",
        "label": "Fresh research-reviewer per round.",
        "pass": "PASS",
        "cap": "5 rounds with you around, 10 unattended"
       },
       "loop": {
        "to": "deep-dives",
        "label": "FINDINGS: the same author revises",
        "short": "max 5 rounds · 10 unattended",
        "cap": "5 rounds attended, 10 unattended; then it reaches you as unresolved"
       },
       "out": [
        "`research/deep-dive-<topic>.md`",
        "`research/reviews/<topic>-NN.md`"
       ],
       "sources": [
        "docs/guides/client-workflow.md:210-229",
        ".claude/skills/new-client/SKILL.md:40-47"
       ]
      },
      {
       "id": "follow-up",
       "title": "One follow-up",
       "actor": "lead",
       "with": [
        "owner",
        "client"
       ],
       "summary": "The gap list plus research questions, in one batch, simple Greek. Then the client is not asked again unless you decide.",
       "does": [
        "Chat: aim for 5 questions, never more than 10.",
        "As a form: about 15 minutes, at most 5 typed answers.",
        "Claude updates `facts.md`; anything still missing is left out or marked not supplied."
       ],
       "you": "Send the follow-up and bring the answers back, like the first time.",
       "out": [
        "Updated `intake/facts.md`"
       ],
       "sources": [
        "docs/guides/client-workflow.md:233-245"
       ]
      }
     ]
    },
    {
     "id": "text",
     "title": "Text",
     "steps": [
      {
       "id": "text-draft",
       "title": "Text Draft",
       "actor": "lead",
       "summary": "The CV's words as a PDF in the fixed house design, First Fitting. Every fact to check carries a copper `Fact Mark`.",
       "does": [
        "Page 1 is the `Check Page` in Greek: \"check only the underlined facts; the wording is ours; reply OK\".",
        "Then the content in the CV's language, sized for the `Template`.",
        "Claude checks every page before giving you the path."
       ],
       "out": [
        "`draft/draft-NN.pdf` with its `Meta File` (status `sent`)"
       ],
       "cmd": [
        "typst compile --root . --font-path packages/cv-framework/fonts private/<envelope>/draft/draft-01.typ private/<envelope>/draft/draft-01.pdf",
        "python scripts/outputs.py stamp private/<envelope>/draft/draft-01.pdf status=sent"
       ],
       "sources": [
        "docs/guides/client-workflow.md:249-272",
        "scripts/text-draft.typ:1-6"
       ]
      },
      {
       "id": "sign-off",
       "title": "Sign-off",
       "actor": "owner",
       "with": [
        "client"
       ],
       "summary": "The client's \"OK, the facts are correct\". Not a signature: usually a chat message.",
       "you": "Send the draft. Save the client's OK as a screenshot, `draft/sign-off-NN.png`.",
       "gate": {
        "type": "owner",
        "label": "The client's OK is saved."
       },
       "loop": {
        "to": "text-draft",
        "label": "Corrections: a new draft number; the old one is marked `superseded`",
        "short": "Revise the draft"
       },
       "branch": [
        {
         "to": "build-cv",
         "when": "the Domain already has a Template",
         "short": "marine: skip design",
         "label": "A marine client goes straight to the build: the `Flagship` exists."
        }
       ],
       "does": [
        "A sent draft is never recompiled; its SHA-256 goes in `README.md`."
       ],
       "sources": [
        "docs/guides/client-workflow.md:26",
        "docs/guides/client-workflow.md:272-276",
        "docs/glossary.md"
       ]
      }
     ]
    },
    {
     "id": "design",
     "title": "Design",
     "steps": [
      {
       "id": "design-run",
       "title": "A design run for this client",
       "actor": "lead",
       "with": [
        "magazine-editor"
       ],
       "summary": "Only when the client's `Domain` has no `Template` yet. A design starts from a design, not from code: 18 mock-ups on fictional data.",
       "does": [
        "The `magazine-editor` draws three `Styles` × two `Densities` × three `Design Tiers` for the client's `Domain`, specialty and role.",
        "Fictional data only; no client detail in any brief.",
        "The full run, its gates and caps, is its own page: [[design-run]]."
       ],
       "uses": [
        "idea-run",
        "magazine-editor"
       ],
       "sources": [
        "docs/guides/client-workflow.md:285-295",
        ".claude/skills/new-cv/SKILL.md:62-66"
       ]
      },
      {
       "id": "pick",
       "title": "You pick Style, Tier and Density",
       "actor": "owner",
       "summary": "Your choice from the designs that passed their gates.",
       "you": "Pick one `Style`, one `Design Tier`, one `Density`. Look in the `Design Review` app first if you like.",
       "gate": {
        "type": "owner"
       },
       "uses": [
        "design-review-app"
       ],
       "sources": [
        "docs/guides/client-workflow.md:291-295",
        ".claude/skills/idea-run/SKILL.md:122-134"
       ]
      },
      {
       "id": "build-cv",
       "title": "Build the CV",
       "actor": "lead",
       "with": [
        "design-reviewer"
       ],
       "summary": "The `new-cv` skill builds from `facts.md` and the signed-off text: no re-asking the client, no rewording beyond fitting the page.",
       "does": [
        "Marine: `cv.typ` imports the marine `Domain` with `Flagship`, a `Theme`, artwork and a page plan.",
        "No `Template` yet: a one-off `Template` in the `Envelope`, recorded as a `Framework Gap`.",
        "Client-design previews go to a fresh `design-reviewer` before you see them; it never reads `private/`."
       ],
       "gate": {
        "type": "review",
        "label": "Fresh design-reviewer per round on the previews.",
        "pass": "PASS on `Batch Test`, `Three-Second Test`, `Flagship Parity`",
        "cap": "5 attended, 10 unattended, unless you set another"
       },
       "loop": {
        "to": "build-cv",
        "label": "FINDINGS: Claude fixes the design",
        "short": "max 5 rounds · 10 unattended"
       },
       "out": [
        "`candidate.json`, `cv.typ`",
        "`reviews/design-NN.md` (in the `Envelope`)"
       ],
       "uses": [
        "new-cv",
        "design-reviewer"
       ],
       "sources": [
        ".claude/skills/new-cv/SKILL.md:12-15",
        ".claude/skills/new-cv/SKILL.md:67-85",
        "docs/guides/build-a-cv.md:37-68"
       ]
      }
     ]
    },
    {
     "id": "deliver",
     "title": "Deliver",
     "steps": [
      {
       "id": "render",
       "title": "Render a Revision",
       "actor": "lead",
       "summary": "Every render is a new, never-overwritten folder with a snapshot of its inputs, the PDF, its checks and a `Meta File`.",
       "does": [
        "Checks: page count, no empty page, fonts embedded, text inside the page.",
        "A certificate expired or expiring within 180 days prints a `Certificate Warning`; it never blocks.",
        "Claude stops here and reports the folder, the PDF's hash, the pages and every WARNING word for word."
       ],
       "out": [
        "`revisions/<id>/cv.pdf`",
        "`render.json`, `checks.json`, `cv.meta.json` (status `render`)"
       ],
       "cmd": [
        {
         "cmd": "python scripts/cv.py render private/<envelope>",
         "note": "Add `--pages 1` for the one-page profile, `--pages 3` for three. Exit 2 means refused, nothing written."
        }
       ],
       "uses": [
        "cv-py"
       ],
       "sources": [
        "docs/guides/build-a-cv.md:117-149",
        ".claude/skills/new-cv/SKILL.md:104-114"
       ]
      },
      {
       "id": "approve",
       "title": "Approval",
       "actor": "owner",
       "summary": "Your act on the exact bytes you reviewed. Agents never approve a real client's PDF.",
       "you": "Open the PDF, check it, then approve it by its hash.",
       "gate": {
        "type": "owner",
        "label": "Bound to the revision and its SHA-256. Refused if the bytes changed or the checks failed."
       },
       "cmd": [
        {
         "cmd": "python scripts/cv.py approve private/<envelope> <revision-id> --approver \"<name>\" --sha256 <hash>",
         "who": "you"
        }
       ],
       "out": [
        "`cv.approval.json`",
        "`Meta File` re-stamped `approved`"
       ],
       "uses": [
        "cv-py"
       ],
       "sources": [
        "docs/guides/build-a-cv.md:182-189",
        "docs/pdf-workflow.md:166-170"
       ]
      },
      {
       "id": "export",
       "title": "Export",
       "actor": "lead",
       "summary": "A verified copy of the approved bytes, ready to send. It never compiles anything.",
       "does": [
        "Checks render, checks and approval, copies PDF and receipt, verifies the copy.",
        "A new `Revision` inherits no approval."
       ],
       "cmd": [
        "python scripts/cv.py export private/<envelope> <revision-id>"
       ],
       "out": [
        "`exports/<revision-id>/cv.pdf`"
       ],
       "uses": [
        "cv-py"
       ],
       "sources": [
        "docs/guides/build-a-cv.md:191-206",
        "docs/pdf-workflow.md:171-182"
       ]
      },
      {
       "id": "deliver",
       "title": "Send it",
       "actor": "owner",
       "with": [
        "client"
       ],
       "summary": "Sending is a separate act, by you. Then the record says delivered, with a delete-by date.",
       "you": "Send the exported PDF to the client.",
       "does": [
        "Claude re-stamps the PDF `delivered`.",
        "Writes \"Delivered <date>. Delete by <date + 12 months>\" in the `Envelope`'s `README.md`."
       ],
       "cmd": [
        "python scripts/outputs.py stamp private/<envelope>/revisions/<id>/cv.pdf status=delivered"
       ],
       "sources": [
        "docs/guides/build-a-cv.md:202-204",
        "docs/guides/client-workflow.md:297-300"
       ]
      }
     ]
    },
    {
     "id": "after",
     "title": "After",
     "steps": [
      {
       "id": "retention",
       "title": "12 months later: delete",
       "actor": "owner",
       "summary": "Client data goes 12 months after delivery, unless the client asked to keep it. Deleting is always yours.",
       "you": "Delete the `Envelope`, the `Intake Form`, its Sheet and script project, then empty Drive's Trash (it keeps files 30 days).",
       "gate": {
        "type": "owner",
        "label": "Claude names passed delete-by dates; you do the deleting."
       },
       "sources": [
        "docs/guides/client-workflow.md:297-305",
        "docs/preferences.md:69-78"
       ]
      }
     ]
    }
   ]
  },
  {
   "id": "design-run",
   "kind": "flow",
   "nav": "Design run",
   "title": "A design run: 18 designs to your pick",
   "question": "We drew 18 designs. What happens next, who reviews them, on which model?",
   "summary": "The `idea-run` skill in its design form. One author draws, two kinds of reviewer judge in closed loops, and only you decide. Nothing is built, approved or put on the roadmap without you. The two `Densities` (18 designs) arrived with the 2026-09-29 run.",
   "tldr": [
    "The `magazine-editor` draws 3 `Styles` × 2 `Densities` × 3 `Design Tiers` = 18 Typst mock-ups on fictional data.",
    "Two gates, each a fresh Opus-high reviewer per round: research first, then design, until PASS (cap 5 with you around, 10 unattended). Your own look in the `Design Review` app is optional, any time.",
    "You get a short message with every passed style; your answer becomes `chosen`, `parked`, `rejected` or an `Anti-example`."
   ],
   "sources": [
    ".claude/skills/idea-run/SKILL.md",
    ".claude/agents/magazine-editor.md",
    ".claude/agents/design-reviewer.md"
   ],
   "status": {
    "step": "follows",
    "asOf": "2026-10-04",
    "title": "Hanami Line 2 chosen; every run is on main",
    "note": "Travel & Tourism, Japan, tour leader. After the 2026-09-29 run (Woodblock Road, Stamp Rally, Concourse, never gated) and Japan Passage, Hanami Line and Hanami Line 2 passed both gates; you chose Hanami Line 2 on 2026-10-02 and it was built for the client. All run branches were merged into `main` on 2026-10-04.",
    "waitingOn": [
     "lead"
    ],
    "ref": "design-concepts/README.md"
   },
   "phases": [
    {
     "id": "setup",
     "title": "Set up",
     "steps": [
      {
       "id": "ask",
       "title": "You ask for designs",
       "actor": "owner",
       "with": [
        "lead"
       ],
       "summary": "For a client whose `Domain` has no `Template` yet, or when you want inspiration.",
       "you": "Say which `Domain`, specialty and role the pages must shout, and how many pages Spacious may use (1 to 3).",
       "does": [
        "The lead loads the `idea-run` skill.",
        "A product-ideas run works the same way with `ceo` and `ceo-reviewer` instead; weekly at most."
       ],
       "uses": [
        "idea-run"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:8-21",
        ".claude/skills/idea-run/SKILL.md:36-42"
       ]
      },
      {
       "id": "branch",
       "title": "A branch and a run record",
       "actor": "lead",
       "summary": "Every run lives on its own branch with one record of the brief, the rounds, the verdicts and what reached you.",
       "out": [
        "Branch `docs/idea-run-<date>-editor`",
        "`docs/work/idea-runs/<date>-editor/run.md`"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:32-35"
       ]
      },
      {
       "id": "brief",
       "title": "The brief",
       "actor": "lead",
       "summary": "One steer for the author and the very same steer for every reviewer. Never any client data.",
       "does": [
        "Names the `Domain`, specialty and role the page must shout.",
        "Never bans domain imagery; gives the Spacious page count.",
        "The lead keeps the author's agent id, so revisions go back to the same author with its memory."
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:36-49"
       ]
      }
     ]
    },
    {
     "id": "draw",
     "title": "Draw",
     "steps": [
      {
       "id": "draw",
       "title": "Draw the 18 designs",
       "actor": "magazine-editor",
       "summary": "Three very distinct `Styles`, each drawn Condensed (one dense page) and Spacious (1 to 3 pages), each in Safe, Stylish and Creative.",
       "does": [
        "Studies the vision, the glossary, the `Anti-examples` (never repeat their idea), the design studies and the `Flagship`.",
        "Builds each Style's folder in `design-concepts/` with a brief, fictional sample data, a portrait when the idea needs one, and every PDF with its PNG pages.",
        "At most two open-licence font families per Style. Never touches the engine, examples, tests, archive or `private/`.",
        "Stamps every PDF `proposed` so it shows up in the `Design Review` app."
       ],
       "out": [
        "`design-concepts/<date>-<slug>/condensed/<tier>/…`",
        "`…/spacious/<tier>/…`",
        "18 `Meta Files`, status `proposed`"
       ],
       "cmd": [
        "python scripts/outputs.py stamp <pdf> status=proposed producedBy=magazine-editor"
       ],
       "uses": [
        "magazine-editor",
        "outputs-py"
       ],
       "sources": [
        ".claude/agents/magazine-editor.md:50-82",
        ".claude/agents/magazine-editor.md:88-209",
        "design-concepts/README.md"
       ]
      }
     ]
    },
    {
     "id": "look",
     "title": "Your look",
     "steps": [
      {
       "id": "own-look",
       "title": "Your own look",
       "actor": "owner",
       "summary": "Any time, before or after the gates: the Board shows the run as Style × Density × Tier, the Loupe one design full size, plus a `Batch Test` pile. Nothing waits for it.",
       "you": "Start the app, go through the 18, mark each keep, maybe or reject, star favourites, write notes. Agents read your verdicts from there.",
       "cmd": [
        {
         "cmd": "python scripts/design_review/server.py",
         "who": "you",
         "note": "Then open http://127.0.0.1:8765/"
        }
       ],
       "out": [
        "`.local/design-review/state.json` (your verdicts)"
       ],
       "uses": [
        "design-review-app"
       ],
       "note": "The `idea-run` skill does not place this look at a fixed point in the loop; it is your tool, usable before or after the gates.",
       "sources": [
        "scripts/design_review/server.py:1-12",
        "AGENTS.md",
        "docs/glossary.md"
       ],
       "optional": true
      }
     ]
    },
    {
     "id": "gates",
     "title": "AI gates",
     "steps": [
      {
       "id": "research-gate",
       "title": "Research gate",
       "actor": "research-reviewer",
       "summary": "Every reference a Style rests on is checked: it exists, it is current, it says what is claimed.",
       "gate": {
        "type": "review",
        "label": "Fresh research-reviewer each round, given every earlier report.",
        "pass": "PASS",
        "cap": "5 rounds with you around, 10 unattended"
       },
       "loop": {
        "to": "research-gate",
        "label": "FINDINGS: the author fixes the brief, then a fresh reviewer",
        "short": "max 5 rounds · 10 unattended"
       },
       "does": [
        "Blocking: a load-bearing claim unsourced, misquoted, dead, stale, or opinion stated as fact."
       ],
       "out": [
        "`reviews/NN-research-reviewer.md`"
       ],
       "uses": [
        "research-reviewer"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:50-56",
        ".claude/agents/research-reviewer.md:31-59"
       ]
      },
      {
       "id": "design-gate",
       "title": "Design gate",
       "actor": "design-reviewer",
       "with": [
        "codex-reviewer"
       ],
       "summary": "Every page judged on the three business tests first, then craft. Any of the first three failing is Blocking, however well made.",
       "does": [
        "Makes batch sheets: each page shrunk among 8+ plain market CVs, to judge the `Batch Test` honestly.",
        "Rubric: 1 `Batch Test`, 2 `Three-Second Test`, 3 `Flagship Parity`, 4 distinct, 5 reads as a CV, 6 craft, 7 provenance, 8 buildable.",
        "Also Blocking: a run whose Styles are not very distinct, or a Style repeating an `Anti-example`'s idea.",
        "Planned: the Codex reviewer (GPT-6 Astra, high) looks at the same pages; a round passes only when both pass."
       ],
       "gate": {
        "type": "review",
        "label": "Fresh design-reviewer each round (plus the Codex reviewer once built).",
        "pass": "PASS from every reviewer",
        "cap": "5 attended, 10 unattended. You set 10 for the 2026-09-29 run."
       },
       "out": [
        "`reviews/NN-design-reviewer.md`"
       ],
       "uses": [
        "design-reviewer",
        "codex-reviewer"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:57-65",
        ".claude/agents/design-reviewer.md:44-133",
        "docs/proposals/codex-visual-tools.md"
       ]
      },
      {
       "id": "revise",
       "title": "The author revises",
       "actor": "magazine-editor",
       "summary": "Every Blocking finding is fixed in the page and re-rendered, or argued with evidence. A Style that cannot be saved is replaced: a run always ends with three.",
       "loop": {
        "to": "design-gate",
        "label": "Back to a fresh design-reviewer",
        "short": "next round",
        "cap": "At the cap, the Style reaches you marked `unresolved` with the last reason."
       },
       "does": [
        "Notes (taste, polish) are optional.",
        "After a PASS: a new sourced claim goes back to the research gate; a change to the Style's idea or to what you decide on goes back to the design gate; layout, typos or sample data need only a lead check noted in `run.md`."
       ],
       "sources": [
        ".claude/agents/magazine-editor.md:211-219",
        ".claude/skills/idea-run/SKILL.md:66-71"
       ]
      }
     ]
    },
    {
     "id": "decide",
     "title": "Your decision",
     "steps": [
      {
       "id": "integrate",
       "title": "Integrate",
       "actor": "lead",
       "summary": "The passed run goes to `main`. Designs stay `proposed` until you answer.",
       "does": [
        "`outputs.py check` must pass: every PDF in its home with a valid `Meta File`.",
        "Commit, merge to `main`, push: routine, no approval needed.",
        "Any new glossary terms the author used are added by the lead."
       ],
       "cmd": [
        "python scripts/outputs.py check"
       ],
       "uses": [
        "outputs-py"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:73-85",
        "docs/review.md:48-63"
       ]
      },
      {
       "id": "message",
       "title": "You get a short message",
       "actor": "lead",
       "with": [
        "owner"
       ],
       "summary": "Each Style's three-word idea with its six PDFs, anything dropped or `unresolved`, and how many rounds each gate took.",
       "does": [
        "Styles still waiting for your answer are listed in the `session-handoff` doc."
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:114-122"
       ]
      },
      {
       "id": "decide",
       "title": "You decide each Style",
       "actor": "owner",
       "summary": "Your answer becomes the Style's state, written into its `Meta Files` so the app shows it.",
       "you": "For each Style: build it (say which `Design Tier` and `Density`), later, reject, or \"not my style\".",
       "gate": {
        "type": "owner",
        "label": "Build it → `chosen` · Later → `parked` · Reject → `rejected` · Not my style, keep it → `Anti-example`. No answer: stays `proposed`."
       },
       "sources": [
        ".claude/skills/idea-run/SKILL.md:122-134",
        "docs/pdf-workflow.md:125"
       ]
      },
      {
       "id": "restamp",
       "title": "States are recorded",
       "actor": "lead",
       "summary": "A dated decision line in the concepts README, and the new state re-stamped into the designs' `Meta Files`.",
       "does": [
        "`chosen`: only the picked tier's PDFs are re-stamped.",
        "`rejected`: the folder is removed (Git keeps it) and unused fonts go.",
        "`Anti-example`: moves to `archive/anti-examples/` with its fonts and your reason."
       ],
       "cmd": [
        "python scripts/outputs.py stamp <pdf> status=chosen"
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:122-134",
        "design-concepts/README.md:44-47",
        "archive/anti-examples/README.md"
       ]
      },
      {
       "id": "follows",
       "title": "What follows",
       "actor": "lead",
       "summary": "A chosen Style becomes either a `Template` task in `backlog/` or the client's own CV.",
       "does": [
        "For a client: the one-off design is built and reviewed in their `Envelope`: [[client-journey#build-cv]].",
        "A concept becomes a `Template` only after you keep it and a build task is agreed."
       ],
       "sources": [
        ".claude/skills/idea-run/SKILL.md:129-134",
        "design-concepts/README.md:3-6"
       ]
      }
     ]
    }
   ]
  },
  {
   "id": "change-review",
   "kind": "flow",
   "nav": "A change",
   "title": "How any change lands",
   "question": "When Claude changes something, what happens before it is on main?",
   "summary": "Every change, code or docs or design, goes through an independent review by a fresh agent before it is called done. Routine Git is the agents' job; a short list of irreversible things stays yours.",
   "tldr": [
    "Each session starts from the `session-handoff` doc on `main` (`backlog/docs/`) and ends by rewriting it after a `Session Sweep`.",
    "Build, prove it with `tests/run.py`, then a fresh reviewer per round: `code-reviewer` for code and, on `main`, everything else; `design-reviewer` for looks. A `context-reviewer` reviews changes to agent rules.",
    "Fix every Blocking and Material finding; stop at PASS or after 5 rounds (10 unattended). Then merge, push and watch CI."
   ],
   "sources": [
    "docs/development.md",
    "docs/review.md",
    "docs/git-workflow.md"
   ],
   "status": {
    "step": "merge",
    "asOf": "2026-10-04",
    "waitingOn": [
     "lead"
    ],
    "title": "All branches merged into main",
    "note": "On 2026-10-04 you asked for every branch to be merged so only `main` remains, including `codex-visual-tools` (the two context agents and the approved, not yet built, Codex image and visual-review plan). Its two review reports were FINDINGS and stay open.",
    "ref": "git: main"
   },
   "phases": [
    {
     "id": "start",
     "title": "Start",
     "steps": [
      {
       "id": "orient",
       "title": "The session starts from the handoff doc",
       "actor": "lead",
       "with": [
        "board"
       ],
       "summary": "Claude reads AGENTS.md, your preferences, then the `session-handoff` doc as it stands on `main`, and checks it against Git and the evidence.",
       "does": [
        "Gives you a four-line briefing: Goal, Now, Next, You.",
        "Separates an approved design from built behaviour, and old checks from current proof."
       ],
       "uses": [
        "backlog"
       ],
       "sources": [
        "docs/development.md:34-56",
        "AGENTS.md:35-44"
       ]
      },
      {
       "id": "card",
       "title": "A task file for the task",
       "actor": "lead",
       "with": [
        "board"
       ],
       "summary": "A Backlog.md task in `backlog/tasks/` is the task record: outcome, acceptance, plan, result and evidence, review, handoff. It changes on the branch doing the work.",
       "does": [
        "Statuses: Queued → Active → Review → Ready → Done. The `blocked` label when stuck.",
        "Ready is not Done: Done means on its branch, pushed, CI green, evidence recorded."
       ],
       "uses": [
        "backlog"
       ],
       "sources": [
        "docs/development.md:17-32",
        "docs/development.md:113-201"
       ]
      }
     ]
    },
    {
     "id": "build",
     "title": "Build",
     "steps": [
      {
       "id": "branch",
       "title": "A branch, or straight to main",
       "actor": "lead",
       "summary": "Small verified fixes and docs may go straight to `main`. Features and anything uncertain get a `<type>/<topic>` branch, often in a worktree. No pull requests.",
       "sources": [
        "docs/git-workflow.md:21-33",
        "docs/git-workflow.md:61-65"
       ]
      },
      {
       "id": "build",
       "title": "Build it and prove it",
       "actor": "lead",
       "summary": "Understand the seam first, then change it, then run the full suite. A visual change also needs a rendered page.",
       "does": [
        "Evidence goes to a new `builds/tests-<timestamp>/` folder; nothing is overwritten.",
        "Going around a component? It gets a `Framework Gap` entry before \"done\"."
       ],
       "cmd": [
        "python tests/run.py"
       ],
       "uses": [
        "verify-cv",
        "suite"
       ],
       "sources": [
        "AGENTS.md",
        ".claude/skills/verify-cv/SKILL.md:10-17"
       ]
      }
     ]
    },
    {
     "id": "review",
     "title": "Review",
     "steps": [
      {
       "id": "review",
       "title": "Independent review",
       "actor": "code-reviewer",
       "with": [
        "design-reviewer",
        "context-reviewer"
       ],
       "summary": "A fresh agent that never saw the work judges the exact snapshot. Which reviewer depends on what changed.",
       "does": [
        "Code, tests, fixtures, and on `main` every change no other gate covers: `code-reviewer`.",
        "Looks: CV pages, brand assets, `Flagship` changes: `design-reviewer`.",
        "Agent context (AGENTS.md, rules, glossary, skills): `context-reviewer`; a change that mixes code and context gets both.",
        "Eight lenses, from product fit to repository hygiene. Findings are Blocking, Material, Minor or Note."
       ],
       "gate": {
        "type": "review",
        "label": "Verdict PASS, FINDINGS or INCOMPLETE (never treated as PASS).",
        "pass": "no open Blocking or Material",
        "cap": "5 rounds with you around, 10 unattended"
       },
       "out": [
        "`docs/work/<task>/reviews/NN.md`, stored unchanged"
       ],
       "uses": [
        "code-reviewer",
        "design-reviewer",
        "context-reviewer"
       ],
       "note": "Only spelling, comments, formatting or a glossary row skip the round, and record-keeping commits (storing reports, merging reviewed work).",
       "sources": [
        "docs/review.md:7-63",
        "docs/review.md:80-100",
        "docs/review.md:156-175",
        "docs/review.md",
        "docs/work/anti-examples/reviews/01-context.md"
       ]
      },
      {
       "id": "fix",
       "title": "Fix Blocking and Material",
       "actor": "lead",
       "summary": "Each report is kept word for word with the lead's dispositions beside it. Blocking and Material get fixed; the checks run again.",
       "loop": {
        "to": "review",
        "label": "A fresh reviewer, given every earlier report",
        "short": "max 5 rounds · 10 unattended",
        "cap": "At the cap the task stays unresolved and comes to you; more rounds need your decision."
       },
       "does": [
        "Minor: fix it or record why it waits. Notes do not block.",
        "Renaming the task never resets the round count."
       ],
       "sources": [
        "docs/review.md:179-205"
       ]
      }
     ]
    },
    {
     "id": "land",
     "title": "Land",
     "steps": [
      {
       "id": "merge",
       "title": "Merge, push, watch CI",
       "actor": "lead",
       "with": [
        "github-ci"
       ],
       "summary": "Merging into `main` is routine and the agents' job. `main` must always be releasable.",
       "does": [
        "Required checks before the push, then `gh run watch` until CI is green.",
        "Then the task moves to Done with its evidence, as a record commit on `main`."
       ],
       "cmd": [
        "gh run list --commit <sha>",
        "gh run watch <run-id>"
       ],
       "note": "Yours only, with the exact command shown first, including: deleting or force-pushing `main`, rewriting its published history, `archive/*` tags, repo settings, deleting under `private/` or `.local/` or outside the repo, removing revisions, approvals, exports or portraits, replacing the `Release`.",
       "sources": [
        "docs/git-workflow.md:66-79",
        "docs/preferences.md:52-78",
        ".github/workflows/verify.yml"
       ]
      }
     ]
    },
    {
     "id": "close",
     "title": "Close",
     "steps": [
      {
       "id": "sweep",
       "title": "Session Sweep",
       "actor": "lead",
       "summary": "Before stopping, Claude looks in fixed places for loose ends: a list of places to look, never a list of what is open.",
       "does": [
        "Reviews: every commit on `main` since the handoff doc's `Main at` sha has a report or is trivial.",
        "Proposals marked `approved` but not applied; tasks in Active, Review, Ready or labelled `blocked`.",
        "Night Shift follow-ups, Git leftovers, CI on `main`, old `builds/` folders.",
        "Repo health: `/repo-maintenance quick`, a few seconds.",
        "`Atlas`: `atlas.py check`; a stale or unverified page is re-checked against its sources."
       ],
       "uses": [
        "repo-maintenance",
        "night-shift"
       ],
       "sources": [
        "docs/development.md:58-95"
       ]
      },
      {
       "id": "handoff",
       "title": "Rewrite the handoff doc on main",
       "actor": "lead",
       "with": [
        "board"
       ],
       "summary": "The next session starts here: written date, `Main at` sha, where things stand, next steps, your parked decisions, pitfalls.",
       "uses": [
        "backlog"
       ],
       "sources": [
        "docs/development.md:97-111"
       ]
      },
      {
       "id": "report",
       "title": "You get the report",
       "actor": "owner",
       "summary": "A short verbal report and, for finished work, an HTML page. Decisions that need you are named.",
       "you": "Read it, use the product, answer the parked decisions when you are ready.",
       "gate": {
        "type": "owner",
        "label": "Product decisions and real-client approvals stay yours."
       },
       "sources": [
        "docs/preferences.md:49-51",
        "docs/preferences.md:84"
       ]
      }
     ]
    }
   ]
  },
  {
   "id": "system-map",
   "kind": "system",
   "nav": "The parts",
   "title": "What lives where",
   "question": "What are the parts of CVgen and how do they feed each other?",
   "summary": "The repository in nine areas. The main line runs across the top; hover or tap any part to light up what it feeds and what feeds it.",
   "tldr": [
    "A CV is facts (`candidate.json`) poured into a `Template` built on the `Framework`; `cv.py` turns it into a never-overwritten `Revision`.",
    "Every PDF anyone reviews carries a `Meta File`, which is how the `Design Review` app finds it.",
    "Client data lives only in `private/`; everything in Git is fictional."
   ],
   "sources": [
    "AGENTS.md",
    "docs/architecture.md",
    "docs/pdf-workflow.md"
   ],
   "columns": 12,
   "groups": [
    {
     "id": "g-private",
     "title": "Client Envelopes",
     "icon": "lock",
     "kind": "client",
     "col": 1,
     "w": 4,
     "row": 1,
     "blurb": "`private/`: one folder per real client. Ignored by Git, never in a brief.",
     "nodes": [
      {
       "id": "n-envelope",
       "title": "envelope.json + README",
       "path": "private/<envelope>/",
       "blurb": "Who the client is: `Alias`, `Domain`, `Rank`; dates and links.",
       "detail": "`cv.py render` refuses to run without `envelope.json`; every client `Meta File` copies it.",
       "sources": [
        "docs/guides/client-workflow.md:29-77"
       ]
      },
      {
       "id": "n-intake",
       "title": "intake/ · research/",
       "path": "private/<envelope>/intake/",
       "blurb": "Messages, documents, `facts.md`, the `Scout`, `CV Decisions`, `Deep Dives`.",
       "sources": [
        "docs/guides/client-workflow.md:35-57"
       ]
      },
      {
       "id": "n-draft",
       "title": "draft/",
       "path": "private/<envelope>/draft/",
       "blurb": "The `Text Drafts` and the `Sign-off` screenshots.",
       "sources": [
        "docs/guides/client-workflow.md:249-276"
       ]
      },
      {
       "id": "n-cvtyp",
       "title": "candidate.json + cv.typ",
       "path": "private/<envelope>/cv.typ",
       "blurb": "The client's facts and the entry point that composes their CV.",
       "sources": [
        "docs/guides/build-a-cv.md:37-68"
       ]
      },
      {
       "id": "n-revisions",
       "title": "revisions/ · exports/",
       "path": "private/<envelope>/revisions/<id>/",
       "blurb": "Every render in its own folder; approved copies in `exports/`.",
       "sources": [
        "docs/pdf-workflow.md:71-96"
       ]
      }
     ]
    },
    {
     "id": "g-engine",
     "title": "The engine",
     "icon": "package",
     "kind": "lead",
     "col": 5,
     "w": 4,
     "row": 1,
     "blurb": "Typst code that turns facts into pages.",
     "nodes": [
      {
       "id": "n-framework",
       "title": "Framework",
       "path": "packages/cv-framework/",
       "blurb": "The domain-neutral core: page frame, components, data merge, pagination, fonts.",
       "touch": "Changing behaviour every `Domain` shares. It never imports a `Domain`; the suite checks that."
      },
      {
       "id": "n-marine",
       "title": "Marine Domain",
       "path": "packages/domains/marine/",
       "blurb": "Marine facts, wording, rules and artwork; roles Deck and Engine.",
       "touch": "Changing what the marine `Domain` means."
      },
      {
       "id": "n-flagship",
       "title": "Flagship Template",
       "path": "packages/domains/marine/templates/flagship/",
       "blurb": "The marine CV design: adapter, sections, themes, artwork, layouts.",
       "detail": "Six inputs: facts, role, `Theme`, `Artwork Pack`, `Layout`, durations switch.",
       "touch": "Changing what the `Flagship` renders."
      },
      {
       "id": "n-frozen",
       "title": "Frozen Reference",
       "path": "packages/domains/marine/templates/flagship/tests/approved/",
       "blurb": "The v11 PDF the engineer example must match pixel for pixel.",
       "touch": "Never, without a new reference and an ADR."
      }
     ]
    },
    {
     "id": "g-produce",
     "title": "Produce & approve",
     "icon": "term",
     "kind": "tool",
     "col": 9,
     "w": 4,
     "row": 1,
     "blurb": "The scripts that render, approve, export and stamp.",
     "nodes": [
      {
       "id": "n-cvpy",
       "title": "cv.py",
       "path": "scripts/cv.py",
       "actor": "cv-py",
       "blurb": "render · approve · export · status for one `Envelope`.",
       "cmd": [
        "python scripts/cv.py render private/<envelope>"
       ]
      },
      {
       "id": "n-workflow",
       "title": "cv-workflow",
       "path": "packages/cv-workflow/",
       "blurb": "The Python behind it: snapshots, checks, approval bound to a hash, verified export."
      },
      {
       "id": "n-outputs",
       "title": "outputs.py",
       "path": "scripts/outputs.py",
       "actor": "outputs-py",
       "blurb": "Stamps a PDF's `Meta File`; `check` lists every PDF without a valid one.",
       "cmd": [
        "python scripts/outputs.py check"
       ]
      },
      {
       "id": "n-build",
       "title": "build.ps1",
       "path": "scripts/build.ps1",
       "actor": "build-ps1",
       "blurb": "Builds the five examples; `-Release` writes the `Release`."
      }
     ]
    },
    {
     "id": "g-public",
     "title": "Public examples",
     "icon": "image",
     "kind": "tool",
     "col": 1,
     "w": 4,
     "row": 2,
     "blurb": "Fictional people only. What the product shows the world.",
     "nodes": [
      {
       "id": "n-candidates",
       "title": "Example candidates",
       "path": "examples/candidates/",
       "blurb": "Engineer, captain, chief officer, deck cadet, one fictional portrait."
      },
      {
       "id": "n-release",
       "title": "The Release",
       "path": "examples/marine/flagship/",
       "blurb": "Five entry points, each with its PDF and `Meta File` beside it.",
       "touch": "Replacing the `Release` needs your go."
      }
     ]
    },
    {
     "id": "g-design",
     "title": "Design",
     "icon": "palette",
     "kind": "agent",
     "col": 5,
     "w": 4,
     "row": 2,
     "blurb": "Ideas, references and the house design.",
     "nodes": [
      {
       "id": "n-concepts",
       "title": "design-concepts/",
       "path": "design-concepts/",
       "actor": "magazine-editor",
       "blurb": "Every design run's Styles and Tiers, with a README row each (two Densities since the 2026-09-29 run)."
      },
      {
       "id": "n-anti",
       "title": "Anti-examples",
       "path": "archive/anti-examples/",
       "blurb": "Designs you rejected as not your style. Never repeat their idea."
      },
      {
       "id": "n-studies",
       "title": "Design studies",
       "path": "archive/design-studies/",
       "blurb": "Four frozen studies, for inspiration only."
      },
      {
       "id": "n-textdraft",
       "title": "First Fitting",
       "path": "scripts/text-draft.typ",
       "blurb": "The house design every `Text Draft` uses."
      },
      {
       "id": "n-brand",
       "title": "brand/",
       "path": "brand/",
       "blurb": "The needle's-eye logo, the wordmark, the form header."
      }
     ]
    },
    {
     "id": "g-review",
     "title": "Your review",
     "icon": "eye",
     "kind": "owner",
     "col": 9,
     "w": 4,
     "row": 2,
     "blurb": "Where you look and decide.",
     "nodes": [
      {
       "id": "n-app",
       "title": "Design Review app",
       "path": "scripts/design_review/",
       "actor": "design-review-app",
       "blurb": "Board, Loupe, compare, `Batch Test` pile. Reads only `Meta Files`.",
       "cmd": [
        "python scripts/design_review/server.py"
       ],
       "sources": [
        "scripts/design_review/server.py"
       ]
      },
      {
       "id": "n-state",
       "title": "Your verdicts",
       "path": ".local/design-review/state.json",
       "blurb": "keep / maybe / reject, stars, notes. On this machine only; no verdicts recorded as of 2026-10-01.",
       "sources": [
        "AGENTS.md"
       ]
      }
     ]
    },
    {
     "id": "g-context",
     "title": "Agent context",
     "icon": "book",
     "kind": "lead",
     "col": 1,
     "w": 6,
     "row": 3,
     "cols": 2,
     "blurb": "What every agent reads before acting.",
     "nodes": [
      {
       "id": "n-agents-md",
       "title": "AGENTS.md",
       "path": "AGENTS.md",
       "blurb": "The one map: what is where, the commands, the rules."
      },
      {
       "id": "n-docs",
       "title": "docs/",
       "path": "docs/",
       "blurb": "Vision, constitution, architecture, guides, references, ADRs."
      },
      {
       "id": "n-glossary",
       "title": "Glossary",
       "path": "docs/glossary.md",
       "blurb": "The official words. Hover any dotted word here to see one."
      },
      {
       "id": "n-agent-files",
       "title": ".claude/agents/",
       "path": ".claude/agents/",
       "blurb": "The seven agent profiles, with model and tools."
      },
      {
       "id": "n-skills",
       "title": ".claude/skills/",
       "path": ".claude/skills/",
       "blurb": "The nine checklists agents load."
      },
      {
       "id": "n-work",
       "title": "docs/work/",
       "path": "docs/work/",
       "blurb": "Dated records: review reports, run records. Never re-worded."
      }
     ]
    },
    {
     "id": "g-proof",
     "title": "Proof",
     "icon": "beaker",
     "kind": "tool",
     "col": 7,
     "w": 3,
     "row": 3,
     "blurb": "Evidence before \"done\".",
     "nodes": [
      {
       "id": "n-suite",
       "title": "tests/run.py",
       "path": "tests/run.py",
       "actor": "suite",
       "blurb": "The full suite.",
       "cmd": [
        "python tests/run.py"
       ]
      },
      {
       "id": "n-builds",
       "title": "builds/",
       "path": "builds/<timestamp>/",
       "blurb": "Ignored. Every run writes a new folder.",
       "sources": [
        "AGENTS.md"
       ]
      },
      {
       "id": "n-ci",
       "title": "GitHub CI",
       "path": ".github/workflows/verify.yml",
       "actor": "github-ci",
       "blurb": "The suite on every push and every pull request."
      }
     ]
    },
    {
     "id": "g-outside",
     "title": "Outside the repo",
     "icon": "cloud",
     "kind": "service",
     "col": 10,
     "w": 3,
     "row": 3,
     "blurb": "Services the flows use.",
     "nodes": [
      {
       "id": "n-board",
       "title": "Task store",
       "path": "backlog/",
       "actor": "board",
       "blurb": "Every task is a Backlog.md file; sessions start at the `session-handoff` doc on `main`.",
       "sources": [
        ".claude/skills/backlog/SKILL.md:1-35"
       ]
      },
      {
       "id": "n-forms",
       "title": "Google Forms",
       "path": "your Google account",
       "actor": "intake-form",
       "blurb": "Optional `Intake Forms` and their answer Sheets.",
       "sources": [
        "docs/guides/client-workflow.md:91-128"
       ]
      },
      {
       "id": "n-chat",
       "title": "Chat app",
       "path": "Viber · WhatsApp · email",
       "actor": "chat",
       "blurb": "Questions out, answers back, via you.",
       "sources": [
        "docs/guides/client-workflow.md:81-89"
       ]
      }
     ]
    }
   ],
   "edges": [
    {
     "from": "n-chat",
     "to": "n-intake",
     "label": "answers, via you",
     "type": "data"
    },
    {
     "from": "n-forms",
     "to": "n-intake",
     "label": "answers CSV",
     "type": "data"
    },
    {
     "from": "n-cvtyp",
     "to": "n-marine",
     "label": "imports",
     "type": "calls"
    },
    {
     "from": "n-marine",
     "to": "n-framework",
     "label": "builds on",
     "type": "calls"
    },
    {
     "from": "n-flagship",
     "to": "n-marine",
     "label": "belongs to",
     "type": "calls"
    },
    {
     "from": "n-cvpy",
     "to": "n-cvtyp",
     "label": "renders",
     "type": "calls"
    },
    {
     "from": "n-cvpy",
     "to": "n-revisions",
     "label": "new Revision",
     "type": "writes"
    },
    {
     "from": "n-cvpy",
     "to": "n-workflow",
     "label": "runs",
     "type": "calls"
    },
    {
     "from": "n-revisions",
     "to": "n-app",
     "label": "Meta File",
     "type": "data"
    },
    {
     "from": "n-draft",
     "to": "n-app",
     "label": "Meta File",
     "type": "data"
    },
    {
     "from": "n-textdraft",
     "to": "n-draft",
     "label": "house design",
     "type": "calls"
    },
    {
     "from": "n-build",
     "to": "n-release",
     "label": "writes the Release",
     "type": "writes"
    },
    {
     "from": "n-release",
     "to": "n-flagship",
     "label": "renders with",
     "type": "calls"
    },
    {
     "from": "n-candidates",
     "to": "n-release",
     "label": "facts",
     "type": "data"
    },
    {
     "from": "n-release",
     "to": "n-app",
     "label": "Meta File",
     "type": "data"
    },
    {
     "from": "n-concepts",
     "to": "n-app",
     "label": "Meta File",
     "type": "data"
    },
    {
     "from": "n-outputs",
     "to": "n-concepts",
     "label": "stamps",
     "type": "writes"
    },
    {
     "from": "n-anti",
     "to": "n-concepts",
     "label": "never repeat",
     "type": "data"
    },
    {
     "from": "n-app",
     "to": "n-state",
     "label": "your verdicts",
     "type": "writes"
    },
    {
     "from": "n-suite",
     "to": "n-frozen",
     "label": "pixel check",
     "type": "calls"
    },
    {
     "from": "n-suite",
     "to": "n-builds",
     "label": "evidence",
     "type": "writes"
    },
    {
     "from": "n-ci",
     "to": "n-suite",
     "label": "runs",
     "type": "calls"
    },
    {
     "from": "n-skills",
     "to": "n-board",
     "label": "backlog skill",
     "type": "calls"
    },
    {
     "from": "n-envelope",
     "to": "n-cvpy",
     "label": "render needs it",
     "type": "data"
    }
   ],
   "backboneTitle": "The main line: from a client to a PDF you review",
   "backbone": [
    {
     "node": "n-intake",
     "label": "Facts"
    },
    {
     "node": "n-cvtyp",
     "label": "candidate.json + cv.typ",
     "via": "written from"
    },
    {
     "node": "n-flagship",
     "label": "A Template",
     "via": "imports"
    },
    {
     "node": "n-cvpy",
     "label": "cv.py render",
     "via": "rendered by"
    },
    {
     "node": "n-revisions",
     "label": "A Revision",
     "via": "writes"
    },
    {
     "node": "n-app",
     "label": "Your review",
     "via": "Meta File"
    }
   ]
  },
  {
   "id": "roster",
   "kind": "roster",
   "nav": "Who",
   "title": "Who does the work",
   "question": "Which agents, skills and tools exist, and on which model?",
   "summary": "Everyone and everything that acts in the flows: the model and effort each agent runs on, what it may touch, and every step it appears in.",
   "tldr": [
    "Every author and reviewer agent in the repo runs on Opus at high effort: your standing choice for reviewers since 2026-09-26.",
    "A reviewer is always fresh: a new agent each round, given the earlier reports, never a fork of the author.",
    "Not everything here is on `main`: the two Codex steps are approved but not built; the two context agents are on `main` since 2026-10-04."
   ],
   "sources": [
    "docs/review.md:134-144"
   ]
  }
 ],
 "build": {
  "builtAt": "2026-10-06 07:55 UTC",
  "commit": "3db25c2",
  "kit": "1.0",
  "stale": {},
  "verified": {
   "client-journey": {
    "at": "2026-10-06",
    "commit": "3db25c2"
   },
   "design-run": {
    "at": "2026-10-06",
    "commit": "3db25c2"
   },
   "change-review": {
    "at": "2026-10-06",
    "commit": "3db25c2"
   },
   "system-map": {
    "at": "2026-10-06",
    "commit": "3db25c2"
   },
   "roster": {
    "at": "2026-10-06",
    "commit": "3db25c2"
   }
  }
 }
};
